console.log("Starting");
var free = false;
free = true;
var num = 12;
console.log(num);
console.log(free);
var str = "Hello World";
str = "hi: ".concat(num, ", mo ").concat(free);
console.log(str);
var arr = [1, 2, 3];
console.log(arr);
var arr2 = [4, 5, 6];
console.log(arr2);
var obj = { name: "Hoa", age: 18 };
console.log(obj);
var tuple = ["Hello", 10, true];
console.log(tuple);
var fn = function (x, y) { return x + y; };
console.log(fn(5, 3));
var unionType = "Hello";
console.log(unionType);
var voidType = undefined;
console.log(voidType);
var neverType = (function () { throw new Error("Never reached"); })();
console.log("Đố anh thấy em");
