console.log("Starting");
let free = false;
free = true;
let num = 12;
console.log(num);
console.log(free);
let str = "Hello World";
str = `hi: ${num}, mo ${free}`;
console.log(str);
let arr = [1, 2, 3];
console.log(arr);
let arr2 = [4, 5, 6];
console.log(arr2);
let obj = { name: "Hoa", age: 18 };
console.log(obj);
let tuple = ["Hello", 10, true];
console.log(tuple);
let fn = (x, y) => x + y;
console.log(fn(5, 3));
let unionType = "Hello";
console.log(unionType);
let voidType = undefined;
console.log(voidType);
let neverType = (() => { throw new Error("Never reached"); })();
console.log("Đố anh thấy em");
